### ISSUE TITLE
class \CssMin not found

### ISSUE THREAD

**Issue by ghost** [kriswallsmith/assetic#226]
Class 'CssMin' not found in module\AsseticBundle\vendor\assetic\src\Assetic\Filter\CssMinFilter.php on line 72

**Comment by netbrothers-tr** [comment]
> To use the CssMinFilter, you need to get the CssMin library and include it in your code [...]

I just want to clarify: Do you mean [this library](https://github.com/natxet/CssMin) as a valid candidate for the task? If yes, there's also a packagist item for that. It goes by the name [`natxet/CssMin`](https://packagist.org/packages/natxet/CssMin). It worked for me but I had a little trouble finding a matching package because there's quiet a number of CSS minifiers out there. What do you think about an entry in the `"suggest"` config within Assetic's `composer.json`?

**Comment by stof** [comment]
@netbrothers-tr yes, this is the name of the package which has been created by someone to expose this library on Packagist. It is a fork of the original codebase (which was not on github and not on composer), and this fork was not yet there in 2012

**Comment by netbrothers-tr** [comment]
@stof Thank you for answering and clarifying! What about adding it as a "suggest" package in Assetic's `composer.json`?
