### ISSUE TITLE
[Twig extension] Using a template variable in an asset's path?

### ISSUE THREAD

**Issue by EvanK** [kriswallsmith/assetic#60]
I'm using Assetic in a Symfony2 project, from within twig templates.  Problem is, I have an asset whose name is derived from a twig template variable.  For example, I have a variable called **myobject.slug** that has a value of `foobar-baz`.  I need to process `web/css/foobar-baz.css` with assetic.

I've tried using twig's concatenation operator (the tilde, `~`), and it throws an `Unexpected token "operator" of value "~"` exception:

```
{% stylesheets filter='?yui_css'
    'css/' ~ myobject.slug ~ '.css'
%}
    <link href="{{ asset_url }}" rel="stylesheet" media="screen" />
{% endstylesheets %}
```

Is there a way to accomplish this, currently?  If not, perhaps there ought to be?

**Comment by giordanovi** [comment]
I think you can use the Twig double quote variables escape ( #{twig.variable} ) like:

```
{% stylesheets "css/#{myobject.slug}.css" filter='?yui_css' %}
    <link href="{{ asset_url }}" rel="stylesheet" media="screen" />
{% endstylesheets %}
```

Not tested.

**Comment by wumke** [comment]
I know this is and old issue, but I want to share my way of resolving this issue anyway for the case other users find this issue:

I created a twig template with the stylesheets twig tag and the name of the asset in string format, then i simply include these templates in a loop in my page.html.twig.

This works because the asset is found when iterating all twig files, and only injected in the page render when needed.
