### ISSUE TITLE
Assetic is not aware of asset dependencies

### ISSUE THREAD

**Issue by matteosister** [kriswallsmith/assetic#79]
As discussed [here](https://github.com/kriswallsmith/assetic/issues/43) there is a problem with the new implementation of the compass binary.
The problem is that, the cache system, checks the timestamp of the sass file without involving the filter.
So if you have a main file which imports other "subfiles" (a typical situation working with compass) and you never edit this main file you never get a recompile.

The process of check the timestamp of an assetic file should in some way involve the filter to get a complete list of files to check and eventually trigger the recompile by checking all the timestamps.

This issue is related to compass, but I think it should also appear in Sass and ScssFilter and also on any filter that deal with an asset with a tree of subassets

**Comment by lokhman** [comment]
@stof the issue doesn't seem to be resolved yet for SASS/SCSS.

**Comment by sonu27** [comment]
@stof We are still having this issue for SCSS files.
```
sass:
            bin:      "/usr/bin/sass"
            no_line_comments: true
            apply_to: "\.scss$"
            http_path: /
            images_dir: %kernel.root_dir%/../web/images
            generated_images_path: %kernel.root_dir%/../web/images
            http_generated_images_path: /images
```

**Comment by kniziol** [comment]
@stof Not working for me. Details below. What should I do now?

**/app/config/parameters.yml**
```
# This file is auto-generated during the composer install
parameters:
    (...)
    compass_bin_path: /usr/bin/compass
    nodejs_bin_path: /usr/local/bin/node
    uglifyjs2_bin_path: /usr/local/bin/uglifyjs
    uglifycss_bin_path: /usr/local/bin/uglifycss
    (...)
```

**/app/config/config.yml**
```
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [<all required bundles>]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        sass: ~
        compass:
            bin: %compass_bin_path%
            node: %nodejs_bin_path%
        uglifyjs2:
            bin: %uglifyjs2_bin_path%
            node: %nodejs_bin_path%
        uglifycss:
            bin: %uglifycss_bin_path%
```

**/src/bundles/MyBundle/Resources/views/Pages/Index/index.html.twig**
```
{% stylesheets output='css/homepage.css' filter='compass, ?uglifycss'
    '@MyBundle/Resources/sass/homepage.scss'
%}
    <link rel="stylesheet" type="text/css" href="{{ asset_url }}" />
{% endstylesheets %}
```

**/src/bundles/MyBundle/Resources/sass/homepage.scss**
```
@import 'common';

.main-content {
(...)
```

**/src/bundles/MyBundle/Resources/sass/_common.scss**
```
//
// Variables: colors
//
$font-color: #4e4b4b;
$dark-blue: #0471CC;
(...)
```

**/composer.json**
```
(...)
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.6.*",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "~1.2",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0",
        "sensio/framework-extra-bundle": "~3.0",
        "incenteev/composer-parameter-handler": "~2.0",
(...)
```

**Comment by liviucmg** [comment]
Can confirm that, while assetic:watch reports that the files have been changed, the compiled .css files are not updated. Tried updating composer dependencies and gems, and also tried both the latest tag and latest dev-master of Assetic. Still nothing. :(

**Comment by sonu27** [comment]
@stof @kriswallsmith Could this issue be reopened please?

**Comment by perk11** [comment]
Experiencing exactly the same issue as @liviucmg here

**Comment by henrypenny** [comment]
Going off on a tangent here. I'm guessing many people will be using Gulp or Grunt. Adding the ability for assetic:dump to target a single asset will give a lot of people the ability to use those tools to watch for changes while still having assetic work its magic on the individual assets themselves.

E.g.

use Gulp to watch: `Resouces/public/sass/**.*`,

use assetic to dump: `Resources/public/scss/main.scss`

It will also eliminate the need to re-invent the wheel inside assetic/symfony when there are great tools already available. (Gulp, Grunt)

**Comment by moezkorkmaz** [comment]
Same here. Watching imported assets does not work.

Also I'm not interested in installing Gulp or whatever for just watching the SASS files. I bet there are also others thinking the same. So no need to re-invent the wheel but fixing the issue would be great :-)

**Comment by henrypenny** [comment]
@moezkorkmaz the issue is that Assetic _would_ need to re-invent the wheel by resolving sass imports. Something that is done by libsass if you use gulp.

From the gulp-sass page (https://www.npmjs.com/package/gulp-sass):

gulp-sass is a very light-weight wrapper around node-sass, which in turn is a Node binding for libsass, which in turn is a port of Sass.

There are a couple of libsass wrappers for php:

https://github.com/sass/libsass/blob/master/docs/implementations.md#php

Perhaps these would be a starting point. But it would involve adding an extra php extension to your environment.

**Comment by matteosister** [comment]
I would suggest to get rid of assetic and php to manage assets. In my opinion it's not worth it. Better go with javascript and a build tool like webpack or gulp.

**Comment by MatthiasKuehneEllerhold** [comment]
@henrypenny As far as I know Assetic knows about asset dependencies. The sass filter parses the file and resolves all imports in it. See `ScssphpFilter::getChildren()`

**Comment by mpdude** [comment]
Forget about Assetic, come up with a build process using front end tools like Gulp and get things like CSS livereload for free. Plus a performance boost on development as Assetic makes Symfony really slow, at least five years ago when I last checked.

**Comment by MatthiasKuehneEllerhold** [comment]
@mpdude Is this your opinion as a maintainer or as an user?

**Comment by stof** [comment]
@MatthiasKuehneEllerhold my recommendation as one of the Assetic maintainers is indeed to switch to a stack built directly using frontend tools if it can fit your workflow.

There are 2 different ways to use Assetic:
- using only tools written in PHP. But the issue is that most of them are ports of the original tools written in other languages (Node.js for most of them nowadays, but also Ruby or Java for older ones), which are badly maintained and often far behind the original project in term of features because the original project moves very fast.
- using Assetic filters calling the original tool directly. But then, Assetic is far behind regarding support for configuration settings (as we just don't have resources to update these filters each time one of these projects adds a new option), and it brings no benefit compared to using the tool in a frontend stack (where the integration is generally much better as it is supported by the tool maintainers themselves).

In the second case, my recommendation is clear: stop using Assetic and switch to Gulp or equivalent.
If you are in the first case, consider whether you can switch to the second case, and keep using Assetic otherwise.

Assetic was written at a time available tools were mostly Java and Ruby ones, with no easy way to build a stack combining them automatically. But the ecosystem has evolved a lot since 2011.

**Comment by mpdude** [comment]
@matthiaskuehneellerhold I dug deeper into Assetic a few years ago, also trying to solve this particular issue. I had to learn that it is not worth the hassle and so I can only endorse what @stof says.

As I was mostly using SASS and cssrewrite, the transition over to Gulp was pretty straightforward. I should have a how-to presentation lying somewhere around (in German), email me when you're interested.

**Comment by MatthiasKuehneEllerhold** [comment]
Now thats a grim outlook. We just started a new project and integrated assetic in it. I was worried that it might be abandoned due to 100+ open PRs and no commit for half a year but all the other options weren't as good. I really liked the ZF integration...
Thanks for your opinions!

**Comment by stof** [comment]
@MatthiasKuehneEllerhold lots of opened PR are about adding new filters dealing with more Node.js tools. And as I had few time to dedicate to Assetic these past months (and @kriswallsmith even less than me), adding more filters we don't use and we would have to maintain is not something we rushed about, especially given that we know that they would become outdated a few weeks later when the tool adds new options.

**Comment by henrypenny** [comment]
@MatthiasKuehneEllerhold @stof I had some success writing my own assetic filter some time ago. 

https://github.com/henrypenny/hmp-assetic-bundle

Its basically a copy and paste of the cssrewrite filter. But it handles `@AppBundle:css/mycss.css` references and doesn't require `assets:install --symlink`.

From memory it was working reasonably well with my use case. I could set up watches in grunt or gulp and get assetic to dump them. But that approach dumps everything at once - css, images, js - which is far too slow.

I wanted to be able to target a single sass file like so:

`app/console assetic:dump '@AppBundle/css/style.scss``

But I didn't get that far.

Targeting single files with assetic:dump would allow assetic to remain lightweight and let other frontend tools do the heavily lifting. But we could still have the benefits that assetic offers with regard to managing frontend resources from multiple bundles etc.

**Comment by alex-pex** [comment]
@stof an alternative I didn't try: https://github.com/romanschejbal/gassetic

**Comment by stof** [comment]
Well, I don't see the benefit of gassetic compared to using gulp directly. Replacing the Gulp config file (which can contain code) with a YAML used to generate it seems to me like it may suffer from the same limitations about tool support (but I may be wrong as I just looked at it quickly).
Thus, it looks like it would have to replace the content of the Twig template when running the command, which looks like a weird integration (and would not allow benefiting from the Symfony Asset component features like cache busting). I think referencing the dumped asset directly rather than adding the gassetic layer.

**Comment by henrypenny** [comment]
@stof how hard would it be to modify assetic:dump to target a single asset - or better still a list of assets?

**Comment by stof** [comment]
Well, there is some challenge here, because asset names in the manager are truncated sha1 hashes by default (and I doubt many people are naming their assets explicitly in Twig, as I'm not even sure we ever documented how to do it). So you would have a hard time passing the argument.

**Comment by henrypenny** [comment]
IMO ideally one would reference assets like this:

`app/console assetic:dump @AppBundle:sass/style.scss`.

How does assetic resolve `@AppBundle:sass/style.scss` when templates are parsed?
Surely this logic must already exist?

note: I had some success referencing sass assets like this in an experimental copy of cssrewrite I did a while back.

Do you think this conversation deserves its own issue?

**Comment by stof** [comment]
@henrypenny the issue is that this is **not** the asset being added in the manager (and so dumped). What you need is to reference the ``{% stylesheet %}`` tag added in your template, not a small part of its configuration.

**Comment by stof** [comment]
and yes, please move this to a dedicated issue
