### ISSUE TITLE
SassFilter does work in load instead of dump

### ISSUE THREAD

**Issue by connorjclark** [kriswallsmith/assetic#885]
Is there a reason for this?

I have a worker that loads the content of assets to use a Cachebusting hash. I feed it "getContent()" after "BaseAsset::load()" has run - so it processes filter loads.

The uglifyjs filter does its work in dump, which is great. But the SassFilter does it in load. Is there a reason?

I may end up overloading this filter and swapping the dump/load implementations. But would be nice to  defer this compilation in this package if possible.

**Comment by stof** [comment]
that would totally change the behavior of the filter. And regarding the semantic of load and dump for Assetic filters, that would be wrong (`load` is for anything happening before the concatenation of the different assets of a collection). That's a very risky change regarding BC

This distinction between load and dump phases might have been a mistake in the Assetic architecture.  Representing the concatenation itself as a filter might have been better.
But this would require a huge rewrite of Assetic, and given that it is not really maintained anymore (@kriswallsmith stopped maintaining years ago, and I also stopped spending time on Assetic as I'm not using anymore since 2 years either), this is unlikely to ever happen.

**Comment by connorjclark** [comment]
Ah, I misunderstood the difference between load and dump. I'm not quite sure _what_ would break with such a change, but I understand the hesitation. As a workaround, I will just disable all filters before getting the content, for cache busting purposes. I'll close this ticket.

Regarding a separate filter for concatenation, that would have been very helpful for implementing source maps. I am working on a workaround that is (nearly) operational that uses a worker to "flatten" an AssetCollection into a flat set of Assets called an AssetBag, and applies a filter on the AssetBag that feeds everything through UglifyJS w/ source maps enabled.
